services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - registry_data:/var/lib/registry 
    
    networks:
      - admin_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.ddignac.fr`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
      
      - "traefik.http.routers.registry.service=registry-service"
      - "traefik.http.services.registry-service.loadbalancer.server.port=5000"
      - "traefik.http.services.registry-service.loadbalancer.server.scheme=http"
      - "traefik.http.routers.registry.middlewares=authentikAuth@file"

  registry_ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry_ui
    restart: unless-stopped
    environment:
      REGISTRY_URL: https://registry.ddignac.fr:444/v2
      NGINX_PROXY_URL: https://registry-ui.ddignac.fr
      DELETE_IMAGES: "true"
      
    networks:
      - admin_net # Pour communiquer avec Traefik et Authentik
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.rule=Host(`registry-ui.ddignac.fr`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.registry-ui.middlewares=authentikAuth@file"

      
networks:
  admin_net:
    external: true



volumes:
  registry_data:
    external: true