services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-latest}
    container_name: jellyfin
    ports:
      - "8096:8096"
    user: "${MEDIA_UID:-1100}:${MEDIA_GID:-1100}"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - downloads:/media:ro
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://tv.${DOMAIN_NAME}
    networks:
     - dmz_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`tv.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.middlewares=securityHeaders@file"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
  transmission:
    image: lscr.io/linuxserver/transmission:${TRANSMISSION_VERSION:-latest}
    container_name: transmission
    ports:
      - 9091:9091 #TODO DELETE (handled by traefik) 
    networks:
      - admin_net
    environment:
      - PUID=${MEDIA_UID:-1100}
      - PGID=${MEDIA_GID:-1100}
      - TZ=Etc/UTC+1
    volumes:
      - transmission-config:/config
      - downloads:/downloads
      - softwares:/downloads/softwares
      - torrent-watch:/watch
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`torrent.${DOMAIN_NAME}`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.tls.certresolver=letsencrypt"
      - "traefik.http.routers.transmission.middlewares=adminWhitelist@file,securityHeaders@file,authentikAuth@file"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  samba:
    image: dperson/samba:latest
    container_name: media-smb
    ports:
      - "139:139"
      - "445:445"
    environment:
      TZ: Europe/Paris
      USER: "${SAMBA_USER};${SAMBA_PASSWORD}"
      SHARE: "downloads;/downloads;yes;no;no;${SAMBA_USER};none;${SAMBA_USER};Media downloads"
      WORKGROUP: "${SAMBA_WORKGROUP:-WORKGROUP}"
      GLOBAL2: "create mask = 0664"
      GLOBAL3: "directory mask = 2775"
    volumes:
      - downloads:/downloads
    restart: unless-stopped
    networks:
      - admin_net


volumes:
  transmission-config:
  softwares:
  downloads:
  jellyfin-cache:
  jellyfin-config:
  torrent-watch:

networks:
  dmz_net:
    external: true
  admin_net:
    external: true