
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    restart: unless-stopped
    ports:
      - "82:80"
      - "444:443"
    env_file:
      - .env
    command:
      - --configFile=/traefik.yml 
      - --providers.file=true 
      - --providers.file.filename=/traefik.yml
      - --providers.docker=true
    environment:
      - OVH_ENDPOINT=ovh-eu
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    networks:
      - vpn
      - admin_net
      - dmz_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.ddignac.fr`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$rGvWjRSF$$w0FPvQ/YQc32jPUG8Rvn40"
      - "traefik.http.routers.dashboard.middlewares=auth@docker,admin-net-whitelist@file"

networks:
  admin_net:
    external: true
  dmz_net:
    external: true
  vpn:
    external: true

