log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic/
    watch: true

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: dorian@ddignac.fr
      storage: acme.json
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10
  letsencryptHTTP:
    acme:
      email: dorian@ddignac.fr
      storage: acme-http.json
      httpChallenge:
        entryPoint: websecure