providers:
  docker:
    exposedByDefault: false
  file:
    filename: /middleware.yml 
    watch: true

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: dorian@ddignac.fr
      storage: acme.json
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10