version: '2'

volumes:
  media_softwares:
    external: true
  onlyoffice_data:
  data:
  config:
  custom_apps:

networks:
  mariadb:
    external: true
  vpn:
    external: true

services:

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - 85:80
    restart: always
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - custom_apps:/var/www/html/custom_apps
#      - media_softwares:/var/www/html/logiciels
    environment:
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=${DB_HOST}
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=4096M
    networks: 
      - mariadb
      - vpn

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
    networks:
      - vpn  