services:

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: always
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - custom_apps:/var/www/html/custom_apps
      - media_softwares:/var/www/html/logiciels
    environment:
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=${DB_HOST}
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=4096M
    networks:
      - db_mariadb_net
      - dmz_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dmz_net"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN_NAME}`) || Host(`drive.${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"

  onlyoffice:
    image: onlyoffice/documentserver:${ONLYOFFICE_VERSION}
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
    networks:
      - dmz_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`office.${DOMAIN_NAME}`)"
      - "traefik.http.routers.onlyoffice.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice.tls.certresolver=letsencrypt"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"

      - "traefik.http.middlewares.onlyoffice-headers.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.onlyoffice-headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000"
      - "traefik.http.middlewares.onlyoffice-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.onlyoffice-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.onlyoffice-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.onlyoffice-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.onlyoffice-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.onlyoffice-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.onlyoffice-headers.headers.accessControlMaxAge=15552000"

      - "traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice-headers"

volumes:
  media_softwares:
    external: true
  onlyoffice_data:
  data:
  config:
  custom_apps:

networks:
  db_mariadb_net:
    external: true
  dmz_net:
    external: true