services:
  server:
    image:  ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
    restart: unless-stopped
    command: server
    volumes:
      - media:/media
      - templates:/templates
      - /etc/letsencrypt/live:/certs #TODO to delete (Ce volume n'est plus nécessaire car Traefik gère les certificats)
    networks:
      - vpn #TODO TO delete
      - db_postgresql_net
      - dmz_net
      - db_redis_net
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: ${AUTHENTIK_REDIS__HOST}
      AUTHENTIK_POSTGRESQL__HOST: ${AUTHENTIK_POSTGRESQL__HOST}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authentik.middlewares=securityHeaders@file,compressGzip@file" 
      
      - "traefik.http.routers.authentik.service=authentik-service"
      - "traefik.http.services.authentik-service.loadbalancer.server.port=9000"
      - "traefik.http.services.authentik-service.loadbalancer.server.scheme=http" 
      
      - "traefik.http.routers.authentik-output.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-output.entrypoints=websecure"
      - "traefik.http.routers.authentik-output.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authentik-output.service=authentik-service"
      - "traefik.http.routers.authentik-output.middlewares=securityHeaders@file,compressGzip@file"

  worker:
    image:  ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
    restart: unless-stopped
    networks:
      - vpn #TODO TO delete
      - db_postgresql_net
      - db_redis_net
    command: worker
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - media:/media
      - templates:/templates
      - /etc/letsencrypt/live:/certs #TODO to delete (Ce volume n'est plus nécessaire)
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: ${AUTHENTIK_REDIS__HOST}
      AUTHENTIK_POSTGRESQL__HOST: ${AUTHENTIK_POSTGRESQL__HOST}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL__HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL__PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL__USE_TLS}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_EMAIL__USE_SSL}
      AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_EMAIL__TIMEOUT}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}

volumes:
  media:
  templates:

networks:
  vpn: #TODO TO delete
    external: true
  dmz_net:
    external: true
  db_postgresql_net:
    external: true
  db_redis_net:
    external: true