services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${HA_VERSION}"
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:${ESPHOME_VERSION}
    volumes:
      - esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=${ESPHOME_USER}
      - PASSWORD=${ESPHOME_PWD}
volumes:
  config:
  esphome-config: