services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:${HA_VERSION}"
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha.rule=Host(`home.${DOMAIN_NAME}`)
      - traefik.http.routers.ha.entrypoints=websecure
      - traefik.http.routers.ha.tls.certresolver=letsencrypt
      - traefik.http.routers.ha.middlewares=securityHeaders@file,compressGzip@file
      - traefik.http.services.ha-service.loadbalancer.server.url=http://192.168.0.2:8123

  music-assistant:
    image: ghcr.io/music-assistant/server:${MA_VERSION} 
    container_name: music-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ma-data:/data
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    labels:
      - traefik.enable=true
      - traefik.http.routers.ma.rule=Host(`music.${DOMAIN_NAME}`)
      - traefik.http.routers.ma.entrypoints=websecure
      - traefik.http.routers.ma.tls.certresolver=letsencrypt
      - traefik.http.routers.ma.middlewares=securityHeaders@file,compressGzip@file
      - traefik.http.services.ma-service.loadbalancer.server.url=http://192.168.0.2:8095

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:${ESPHOME_VERSION}
    volumes:
      - esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=${ESPHOME_USER}
      - PASSWORD=${ESPHOME_PWD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.esphome.rule=Host(`esp.${DOMAIN_NAME}`)
      - traefik.http.routers.esphome.entrypoints=websecure
      - traefik.http.routers.esphome.tls.certresolver=letsencrypt
      - traefik.http.routers.esphome.middlewares=securityHeaders@file,compressGzip@file
      - traefik.http.services.esphome-service.loadbalancer.server.url=http://192.168.0.2:6052


volumes:
  config:
  esphome-config:
  ma-data: