services:
  web:
    image: ${REGISTRY_URL}/antidrop-front:${ANTIDROP_WEB_VERSION}
    environment:
      - API_URL=${API_URL}
    restart: always
    networks:
      - dmz_net
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dmz_net"
      - "traefik.http.routers.antidrop.rule=Host(`antidrop.fr`)"
      - "traefik.http.routers.antidrop.entrypoints=websecure,web"
      - "traefik.http.routers.antidrop.tls.certresolver=letsencryptHTTP"
      - "traefik.http.routers.antidrop.middlewares=securityHeaders@file"
      - "traefik.http.services.antidrop-service.loadbalancer.server.port=3002"

  api:
    image: ${REGISTRY_URL}/antidrop-api:${ANTIDROP_API_VERSION}
    networks:
      - default
      - db_mariadb_net
    environment:
      - ALIEXPRESS_PUBLIC_KEY=${ALIEXPRESS_PUBLIC_KEY}
      - ALIEXPRESS_SECRET_KEY=${ALIEXPRESS_SECRET_KEY}
      - ZAPIEX_API_KEY=${ZAPIEX_API_KEY}
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOW_ORIGIN=^.*$
      - APP_ENV=prod
    restart: always
    
networks:
  default:
    driver: bridge
  db_mariadb_net:
    external: true
  dmz_net:
    external: true