services:
  web:
    image: ${REGISTRY_URL}/antidrop-front:${ANTIDROP_WEB_VERSION}
    ports:
      - 3002:3002
    environment:
      - API_URL=${API_URL}
    restart: always

  api:
    image: ${REGISTRY_URL}/antidrop-api:${ANTIDROP_API_VERSION}
    ports:
      - 8080:80
    networks:
      - db_mariadb_net
    environment:
      - ALIEXPRESS_PUBLIC_KEY=${ALIEXPRESS_PUBLIC_KEY}
      - ALIEXPRESS_SECRET_KEY=${ALIEXPRESS_SECRET_KEY}
      - ZAPIEX_API_KEY=${ZAPIEX_API_KEY}
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOW_ORIGIN=^.*$
      - APP_ENV=prod
    restart: always
    
networks:
  db_mariadb_net:
    external: true