http:
  middlewares:
    adminWhitelist:
      ipWhitelist:
        sourceRange:
          - "10.3.0.0/24"
          - "192.168.1.0/24"

    securityHeaders:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        contentTypeNosniff: true

    compressGzip:
      compress: true

    basicauth:
      basicAuth:
        users:
          - "admin:$2a$05$sTTis5YfkSHqCvA9KtySuuz9y9FDx4S8Xgr9sxoZuOJustupWb0S2"