services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 10443:9443
    volumes:
      - /etc/letsencrypt/live/npm-3/fullchain.pem:/certs/portainer.crt
      - /etc/letsencrypt/live/npm-3/privkey.pem:/certs/portainer.key
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - admin_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.ddignac.fr`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.service=portainer-service"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
      - "traefik.http.services.portainer-service.loadbalancer.server.scheme=http"

    extra_hosts:
      - "ddignac.fr:10.2.0.254"

volumes:
  data:

networks:
  admin_net: 
    external: true
  vpn:
    external: true
