services:
  wg-easy:
    image: weejewel/wg-easy:${WG_EASY_VERSION}
    container_name: wg-easy
    restart: unless-stopped
    network_mode: host
    environment:
      - WG_HOST=${DOMAIN_NAME}    
      - PASSWORD=${WG_PASSWORD}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.3.0.x
      - WG_DEFAULT_DNS=192.168.0.2
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.3.0.0/24 -o enp5s0 -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.3.0.0/24 -o enp5s0 -j MASQUERADE
      # AllowedIPs = tous les réseaux accessibles via dns
      # inclut LAN + réseaux Docker internes
      - WG_ALLOWED_IPS=192.168.1.0/24,192.168.0.0/24,10.100.0.0/24,10.10.0.0/24,10.30.0.0/24,10.2.0.0/24,10.3.0.0/24
    volumes:
      - wireguard-configs:/etc/wireguard
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard-router.rule=Host(`wireguard.${DOMAIN_NAME}`) || Host(`vpn.${DOMAIN_NAME}`)
      - traefik.http.routers.wireguard-router.entrypoints=websecure
      - traefik.http.routers.wireguard-router.tls.certresolver=letsencrypt
      - traefik.http.routers.wireguard-router.middlewares=adminWhitelist@file,securityHeaders@file
      - traefik.http.services.wg-service.loadbalancer.server.url=http://192.168.0.2:51821
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

 
  unbound:
    image: mvance/unbound:${UNBOUND_VERSION}
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    volumes:
      - unbound-config:/etc/unbound
    environment:
      - TZ=Europe/Paris
    networks:
      dns:
        ipv4_address: ${UNBOUND_IP}

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 54:80/tcp # http web interface
      - 3000:3000/tcp # initial setup web interface
    restart: unless-stopped
    networks:
      dns:
        ipv4_address: ${PIHOLE_IP}
      admin_net:
    volumes:
      - adguard-config:/opt/adguardhome/conf # app configuration
      - adguard-work:/opt/adguardhome/work # app working directory
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.rule=Host(`dns.${DOMAIN_NAME}`)"
      - "traefik.http.routers.adguardhome.entrypoints=websecure"
      - "traefik.http.routers.adguardhome.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adguardhome.middlewares=adminWhitelist@file,securityHeaders@file"
      - "traefik.http.services.adguardhome-service.loadbalancer.server.port=80"


  # pihole:
    # depends_on:
    #   - unbound
    # container_name: pihole
    # image: pihole/pihole:${PIHOLE_VERSION}
    # restart: unless-stopped
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "54:80"
    # dns:
    #   - ${UNBOUND_IP}
    #   - ${DNS_SERVER_1}
    # environment:
    #   TZ: "Europe/Paris"
    #   WEBPASSWORD: ${PIHOLE_PASSWORD}
    #   ServerIP: ${PIHOLE_IP}
    #   DNS1: ${UNBOUND_IP}
    #   DNS2: ${DNS_SERVER_1}
    #   VIRTUAL_HOST: ${PIHOLE_VIRTUAL_HOST}
    #   FTLCONF_dns_listeningMode: 'ALL' # ajouté car pihole dans un réseau docker & je veux l'accès dans le LAN de la maison 
    # hostname: ${PIHOLE_VIRTUAL_HOST}
    # volumes:
    #   - pihole-etc:/etc/pihole
    #   - pihole-dnsmasq:/etc/dnsmasq.d
    # networks:
    #   dns:
    #     ipv4_address: ${PIHOLE_IP}
    #   admin_net:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.pihole.rule=Host(`dns.${DOMAIN_NAME}`)"
    #   - "traefik.http.routers.pihole.entrypoints=websecure"
    #   - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
    #   - "traefik.http.routers.pihole.middlewares=adminWhitelist@file,securityHeaders@file"
    #   - "traefik.http.services.pihole-service.loadbalancer.server.port=80"

    # cap_add:
    #   - NET_ADMIN

volumes:
  wireguard-configs:
  pihole-etc:
  pihole-dnsmasq:
  unbound-config:
  adguard-config:
  adguard-work:

networks:
  admin_net:
    external: true
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: ${DNS_SUBNET}